swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /transactions:
    get:
      tags:
        - Transaction Module
      summary: Get Transactions for Current Month
      description: Retrieve all transactions for the current month grouped by account.
      parameters:
        - in: query
          name: month
          type: string
          description: The month for which transactions should be retrieved
        - in: query
          name: transactionType
          type: string
          description: Filter by transaction type (e.g., income, expense)
        - in: query
          name: category
          type: string
          description: Filter by transaction category
        - in: query
          name: note
          type: string
          description: Filter by transaction note
        - in: query
          name: accountNumber
          type: string
          description: Filter by account number
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionList'
        '400':
          description: Invalid request
        '500':
          description: Internal Server Error
  /transactions/{transactionId}:
    get:
      tags:
        - Transaction Module
      summary: Get Transaction Details
      description: Retrieve details of a specific transaction.
      parameters:
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction to retrieve details for.
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      tags:
        - Transaction Module
      summary: Update Transaction Details
      description: Update details of a specific transaction. Can update category and note, but not transaction type.
      parameters:
        - in: path
          name: transactionId
          type: string
          description: ID of the transaction to update.
          required: true
        - in: body
          name: body
          description: Updated transaction data (category and note can be updated).
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction details updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid request
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
  /transactions/accounts:
    get:
      tags:
        - Transaction Module
      summary: Get User Accounts
      description: Retrieve the list of user accounts.
      produces:
        - application/json
      responses:
        '200':
          description: User accounts retrieved successfully
          schema:
            $ref: '#/definitions/UserAccountList'
        '500':
          description: Internal Server Error
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    properties:
      date:
        type: string
        description: Date of transaction.
      description:
        type: string
        description: Transaction description.
      amount:
        type: number
        description: Transaction amount.
      balance:
        type: number
        description: Current balance amount.
      transactionType:
        type: string
        description: Type of transaction (e.g., income, expense).
      category:
        type: string
        description: Transaction category.
      note:
        type: string
        description: Transaction note.
      accountNumber:
        type: string
        description: Account number for the transaction.
  TransactionList:
    type: array
    items:
      $ref: '#/definitions/Transaction'
  UserAccount:
    properties:
      accountNumber:
        type: string
        description: Account number.
      accountName:
        type: string
        description: Account name.
  UserAccountList:
    type: array
    items:
      $ref: '#/definitions/UserAccount'
